(define (integral f a b n)
  (let ((h (/ (- b a) n)))
    (define (yk k)
      (f (+ a (* k h)))
    )
    (define (simpson step total)
      (cond ((= step n) (+ total (yk n)))
            ((= step 0) (simpson 1 (yk 0)))
            ((even? step) (simpson (+ step 1) (+ total (* 2 (yk step)))))
            ((odd? step) (simpson (+ step 1) (+ total (* 4 (yk step)))))      
      )
    )
    (* (/ h 3) (simpson 0 0))
  )
)

(define (cube a) 
  (* (* a a) a)
)

(integral cube 0 1 1000)